apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-pipeline-cpu
  namespace: default
  labels:
    fluent-bit.io.type: "Pipeline"
    fluent-bit.io.service: "FluentBit"
    fluent-bit.io.category: "CPU-metrics"
data:
  pipeline_cpu.yaml: |
    pipeline:
      inputs:
        - name: cpu
          tag: my_cpu
      outputs:
        - name: stdout
          match: 'my*cpu'
