apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-pipeline-memory
  namespace: default
  labels:
    fluent-bit.io.type: "Pipeline"
    fluent-bit.io.service: "FluentBit"
    fluent-bit.io.category: "Memory-metrics"
data:
  pipeline_memory.yaml: |
    pipeline:
      inputs:
        - name: mem
          tag: my_mem
      outputs:
        - name: stdout
          match: 'my*mem'
